# Generated by Django 2.0.4 on 2018-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180422_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Indlæg', 'verbose_name_plural': 'Indlæg'},
        ),
    ]
