# Generated by Django 2.0.4 on 2018-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_seo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='seo_desc',
            field=models.CharField(blank=True, default='Portfolio og personlig hjemmeside for Mark Petersen', max_length=120, null=True),
        ),
    ]
