# Generated by Django 2.0.4 on 2018-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
