# Generated by Django 2.0.4 on 2018-06-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180618_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name': 'Teknologi', 'verbose_name_plural': 'Tecknologier'},
        ),
    ]
