# Generated by Django 2.0.4 on 2018-04-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180422_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekter'},
        ),
    ]
