# Generated by Django 2.0.4 on 2018-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20180422_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, default='', max_length=120, null=True),
        ),
    ]
