# Generated by Django 2.0.4 on 2018-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
